version: '3'

services:
    # pgsql_5432:
    #     container_name: pgsql_5432
    #     restart: always
    #     network_mode: bridge
    #     image: postgres:latest
    #     environment:
    #         POSTGRES_PASSWORD: postgres
    #         POSTGRES_USER: postgres
    #         POSTGRES_DB: postgres
    #     volumes:
    #         - ./db/data:/var/lib/pgsql/data
    #         - ./db/init:/docker-entrypoint-initdb.d/
    #     ports:
    #         - 5432:5432
    api:
        container_name: api_8080
        restart: always
        network_mode: bridge
        build: ./
        env_file:
            - .env
        ports:
            - 8080:8080
        # depends_on:
        #     - pgsql_5432
